In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

import os
current_directory = os.getcwd()

In [ ]:
print(current_directory)
covid_path = "../data/hrv-covid19/data/"

# scalesdf = pd.read_csv("scales_description.csv")
hrvdf = pd.read_csv(covid_path + "hrv_measurements.csv")
hrvdf.head()

/content

,user_code,rr_code,measurement_datetime,time_of_day,bpm,meanrr,mxdmn,sdnn,rmssd,pnn50,...,lf,hf,vlf,lfhf,total_power,how_feel,how_mood,how_sleep,tags,rr_data
0,007b8190cf,10489a6aea,2020-04-21 21:23:08,morning,75,795.90,0.12,45.802,54.174,15.15,...,508.0,1076.0,267.0,0.472,1851.0,0,-1,NaN,COVID-19; Workout; Sex; Hobby; Studying; Sleep...,"819,1008,831,847,785,778,866,839,801,793,846,8..."
1,007b8190cf,9610d4d4dc,2020-04-26 11:19:25,morning,70,858.00,0.11,32.889,33.022,16.16,...,409.0,310.0,176.0,1.319,895.0,0,0,0.0,NaN,"888,775,811,883,890,894,894,899,893,889,890,83..."
2,013f6d3e5b,f3de056155,2020-05-15 04:14:21,night,83,724.10,0.17,54.811,65.987,17.17,...,432.0,881.0,194.0,0.490,1507.0,-1,-2,NaN,COVID-19; Fast/Diet; Hungry; Tired; Fever; I c...,"694,832,642,801,751,716,737,742,773,760,701,73..."
3,013f6d3e5b,b04489e32f,2020-05-19 03:06:02,night,75,802.64,0.20,72.223,70.039,22.22,...,814.0,1487.0,1719.0,0.547,4020.0,0,0,NaN,NaN,"821,817,771,805,833,788,747,724,792,825,775,75..."
4,01bad5a519,ac52c706c6,2019-12-31 09:07:43,morning,78,768.07,0.10,29.650,21.196,4.04,...,489.0,128.0,96.0,3.820,713.0,0,0,0.0,NaN,"741,740,734,737,740,731,751,747,745,728,747,76..."

# Objective of Data Exploration


I want to explore HRF data. We want to first investigate the features and statistical data of each of these datasets. I want to find potential correlations between each of these datasets

In [6]:
print("Heart Rate Variabilitiy", hrvdf.shape, hrvdf.columns, "INFO \n",hrvdf.info(), "Description",hrvdf.describe(), hrvdf.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3245 entries, 0 to 3244
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_code             3245 non-null   object
 1   rr_code               3245 non-null   object
 2   measurement_datetime  3245 non-null   object
 3   time_of_day           3245 non-null   object
 4   bpm                   3245 non-null   int64
 5   meanrr                3245 non-null   float64
 6   mxdmn                 3245 non-null   float64
 7   sdnn                  3245 non-null   float64
 8   rmssd                 3245 non-null   float64
 9   pnn50                 3245 non-null   float64
 10  mode                  3245 non-null   float64
 11  amo                   3245 non-null   float64
 12  lf                    3245 non-null   float64
 13  hf                    3245 non-null   float64
 14  vlf                   3245 non-null   float64
 15  lfhf                  3245 non-null   float64
 16  total_power           3245 non-null   float64
 17  how_feel              3245 non-null   int64
 18  how_mood              3245 non-null   int64
 19  how_sleep             1466 non-null   float64
 20  tags                  2201 non-null   object
 21  rr_data               3245 non-null   object
dtypes: float64(13), int64(3), object(6)
memory usage: 557.9+ KB
Heart Rate Variabilitiy (3245, 22) Index(['user_code', 'rr_code', 'measurement_datetime', 'time_of_day', 'bpm',
       'meanrr', 'mxdmn', 'sdnn', 'rmssd', 'pnn50', 'mode', 'amo', 'lf', 'hf',
       'vlf', 'lfhf', 'total_power', 'how_feel', 'how_mood', 'how_sleep',
       'tags', 'rr_data'],
      dtype='object') INFO
 None Description                bpm       meanrr        mxdmn         sdnn        rmssd  \
count  3245.000000  3245.000000  3245.000000  3245.000000  3245.000000
mean     73.257935   839.600366     0.184635    52.489218    52.814196
std      12.201088   137.420367     0.107456    29.369506    39.353213
min      44.000000   477.730000     0.030000     9.515000     6.340000
25%      65.000000   742.490000     0.110000    32.585000    28.985000
50%      72.000000   829.100000     0.160000    46.919000    42.869000
75%      81.000000   925.933000     0.220000    64.406000    62.485000
max     125.000000  1346.740000     0.790000   206.631000   310.800000

             pnn50         mode          amo            lf            hf  \
count  3245.000000  3245.000000  3245.000000   3245.000000   3245.000000
mean     20.615609     0.837465    46.788290    927.038213   1125.041294
std      18.588156     0.144769    16.418873   1455.424089   2490.540413
min       0.000000     0.475000    12.000000      2.000000      4.000000
25%       6.060000     0.725000    35.000000    151.000000    158.000000
50%      16.160000     0.825000    45.000000    423.000000    380.000000
75%      29.290000     0.925000    57.000000   1059.000000    993.000000
max      91.920000     1.325000    98.000000  15522.000000  33490.000000

                vlf         lfhf   total_power     how_feel     how_mood  \
count   3245.000000  3245.000000   3245.000000  3245.000000  3245.000000
mean     578.229892     2.397769   2630.309399    -0.235439    -0.076733
std      876.679652     5.750760   3912.247496     0.706262     0.655032
min        1.000000     0.032000     44.000000    -2.000000    -2.000000
25%      116.000000     0.399000    620.000000    -1.000000     0.000000
50%      293.000000     0.862000   1387.000000     0.000000     0.000000
75%      693.000000     1.966000   2906.000000     0.000000     0.000000
max    18468.000000   105.625000  41118.000000     2.000000     2.000000

         how_sleep
count  1466.000000
mean     -0.065484
std       0.708656
min      -2.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       2.000000   user_code                  0
rr_code                    0
measurement_datetime       0
time_of_day                0
bpm                        0
meanrr                     0
mxdmn                      0
sdnn                       0
rmssd                      0
pnn50                      0
mode                       0
amo                        0
lf                         0
hf                         0
vlf                        0
lfhf                       0
total_power                0
how_feel                   0
how_mood                   0
how_sleep               1779
tags                    1044
rr_data                    0
dtype: int64

The first step is to learn more about these features. R-R intervals refers to the time duration between R-waves or spikes on an ECG for ventricular contraction.
We have a lot of diverse metrics collected about RR frequency: mean, max diff min, standard deviation, nn50 (percentage of normal-tonormal intervals that differ more than 50), mode, modal Amplitude, etc. We also get the power of low frequency and high frequency signals in milliseconds squared? I recognize my lack of domain knowledge in HRV data and will choose not to utilize the HR data above.


# Wearables Profiles

I want to build a profile of each unique user based on their behaviors. Lets start by documenting if the user is a repeating user in the original wearables database. This will allow us to easily filter the profiles we want to build in the future.

In [ ]:
wdf = pd.read_csv(covid_path + "wearables.csv")
print("Wearables", wdf.shape, wdf.columns, "INFO \n",wdf.info(), "Description",wdf.describe(), wdf.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3098 entries, 0 to 3097
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   user_code                        3098 non-null   object
 1   day                              3098 non-null   object
 2   resting_pulse                    1515 non-null   float64
 3   pulse_average                    2089 non-null   float64
 4   pulse_min                        2089 non-null   float64
 5   pulse_max                        2089 non-null   float64
 6   average_spo2_value               40 non-null     float64
 7   body_temperature_avg             65 non-null     float64
 8   stand_hours_total                531 non-null    float64
 9   steps_count                      1968 non-null   float64
 10  distance                         1869 non-null   float64
 11  steps_speed                      1418 non-null   float64
 12  total_number_of_flights_climbed  1235 non-null   float64
 13  active_calories_burned           1200 non-null   float64
 14  basal_calories_burned            3097 non-null   float64
 15  total_calories_burned            3097 non-null   float64
 16  average_headphone_exposure       230 non-null    float64
 17  average_environment_exposure     149 non-null    float64
dtypes: float64(16), object(2)
memory usage: 435.8+ KB
Wearables (3098, 18) Index(['user_code', 'day', 'resting_pulse', 'pulse_average', 'pulse_min',
       'pulse_max', 'average_spo2_value', 'body_temperature_avg',
       'stand_hours_total', 'steps_count', 'distance', 'steps_speed',
       'total_number_of_flights_climbed', 'active_calories_burned',
       'basal_calories_burned', 'total_calories_burned',
       'average_headphone_exposure', 'average_environment_exposure'],
      dtype='object') INFO
 None Description        resting_pulse  pulse_average    pulse_min    pulse_max  \
count    1515.000000    2089.000000  2089.000000  2089.000000
mean       61.409241      78.084251    63.078506    99.456199
std        12.775324      14.366994    14.334455    29.298930
min        40.000000      48.000000    10.000000    48.000000
25%        52.000000      69.000000    53.000000    76.000000
50%        58.000000      76.000000    60.000000    96.000000
75%        69.000000      85.000000    72.000000   118.000000
max       109.000000     163.000000   122.000000   225.000000

       average_spo2_value  body_temperature_avg  stand_hours_total  \
count            40.00000             65.000000         531.000000
mean              0.96100             36.404615           8.986817
std               0.02134              0.239394           5.030643
min               0.92000             35.800000           1.000000
25%               0.94750             36.200000           4.000000
50%               0.96000             36.400000          10.000000
75%               0.98000             36.600000          13.000000
max               0.99000             36.900000          19.000000

        steps_count      distance  steps_speed  \
count   1968.000000   1869.000000  1418.000000
mean    5342.067581   3494.690744    29.700409
std     4761.774987   3599.635544    28.068371
min        1.000000      1.000000     0.010000
25%     1456.000000    772.000000    10.400000
50%     4477.500000   2687.000000    24.575000
75%     7857.250000   5035.000000    44.097500
max    30882.000000  43914.000000   240.000000

       total_number_of_flights_climbed  active_calories_burned  \
count                      1235.000000             1200.000000
mean                         16.202429              750.721667
std                          20.799798              915.538000
min                           1.000000                1.000000
25%                           3.000000               66.000000
50%                           9.000000              180.000000
75%                          22.000000             1597.000000
max                         164.000000             5423.000000

       basal_calories_burned  total_calories_burned  \
count            3097.000000             3097.00000
mean             2258.165644             2549.04908
std               341.462086              804.62248
min                81.000000               81.00000
25%              1968.000000             2001.00000
50%              2271.000000             2353.00000
75%              2569.000000             2668.00000
max              3395.000000             8418.00000

       average_headphone_exposure  average_environment_exposure
count                  230.000000                    149.000000
mean                    64.027348                     54.406040
std                     14.525733                      7.028195
min                     11.650000                     31.560000
25%                     53.607500                     52.020000
50%                     64.395000                     55.150000
75%                     75.215000                     57.180000
max                     92.900000                     73.160000   user_code                             0
day                                   0
resting_pulse                      1583
pulse_average                      1009
pulse_min                          1009
pulse_max                          1009
average_spo2_value                 3058
body_temperature_avg               3033
stand_hours_total                  2567
steps_count                        1130
distance                           1229
steps_speed                        1680
total_number_of_flights_climbed    1863
active_calories_burned             1898
basal_calories_burned                 1
total_calories_burned                 1
average_headphone_exposure         2868
average_environment_exposure       2949
dtype: int64

In [15]:
len(wdf.user_code.unique())
# We get 79 unique users

79

In [48]:
# I want to collect the number of entries per unique user
user_counts =wdf.user_code.value_counts() # Some have 1 entry, some have multiple.

# Lets only use repeated users: > 10 entries
counts = user_counts[user_counts > 10]
len(counts) # Wonderful! There are 49, Let's get
print("User Count Mean", (counts.mean()), "User Count Standard Deviation", user_counts.std())

User Count Mean 61.59183673469388 User Count Standard Deviation 45.89499466761501

Let's look back at our Na data so that we can maximize our dataset. We have a lot of Na values, but we seem to have more complete pulse data (pulse avg, min, and max) as well as steps data (steps_count, distance, and steps_speed). Lets copy our dataset and try to build a new profiles dataframe to learn more about our users.

In [45]:
wdf["isRepeated"] = wdf.user_code.isin(user_counts.index)
wdf["isRepeated"]
print(wdf.head())

    user_code         day  resting_pulse  pulse_average  pulse_min  pulse_max  \
0  007b8190cf  2020-04-26            NaN           70.0       70.0       70.0
1  01bad5a519  2020-02-12            NaN            NaN        NaN        NaN
2  01bad5a519  2020-02-13            NaN            NaN        NaN        NaN
3  01bad5a519  2020-02-15            NaN            NaN        NaN        NaN
4  01bad5a519  2020-02-16            NaN            NaN        NaN        NaN

   average_spo2_value  body_temperature_avg  stand_hours_total  steps_count  \
0                 NaN                   NaN                NaN          NaN
1                 NaN                   NaN                NaN       8574.0
2                 NaN                   NaN                NaN       7462.0
3                 NaN                   NaN                NaN       2507.0
4                 NaN                   NaN                NaN      10131.0

   distance  steps_speed  total_number_of_flights_climbed  \
0       NaN          NaN                              NaN
1       NaN        57.90                              NaN
2       NaN        59.10                              NaN
3       NaN        60.97                              NaN
4       NaN        49.10                              NaN

   active_calories_burned  basal_calories_burned  total_calories_burned  \
0                     NaN                 2859.0                 2859.0
1                     NaN                 2624.0                 2624.0
2                     NaN                 2624.0                 2624.0
3                     NaN                 2624.0                 2624.0
4                     NaN                 2624.0                 2624.0

   average_headphone_exposure  average_environment_exposure  isRepeated
0                         NaN                           NaN       False
1                         NaN                           NaN        True
2                         NaN                           NaN        True
3                         NaN                           NaN        True
4                         NaN                           NaN        True

Now lets

In [47]:
df = wdf.copy()
df = df[df["isRepeated"]] # Only use repeating users

    user_code         day  resting_pulse  pulse_average  pulse_min  pulse_max  \
1  01bad5a519  2020-02-12            NaN            NaN        NaN        NaN
2  01bad5a519  2020-02-13            NaN            NaN        NaN        NaN
3  01bad5a519  2020-02-15            NaN            NaN        NaN        NaN
4  01bad5a519  2020-02-16            NaN            NaN        NaN        NaN
5  01bad5a519  2020-02-17            NaN            NaN        NaN        NaN

   average_spo2_value  body_temperature_avg  stand_hours_total  steps_count  \
1                 NaN                   NaN                NaN       8574.0
2                 NaN                   NaN                NaN       7462.0
3                 NaN                   NaN                NaN       2507.0
4                 NaN                   NaN                NaN      10131.0
5                 NaN                   NaN                NaN       8086.0

   distance  steps_speed  total_number_of_flights_climbed  \
1       NaN        57.90                              NaN
2       NaN        59.10                              NaN
3       NaN        60.97                              NaN
4       NaN        49.10                              NaN
5       NaN        60.14                              NaN

   active_calories_burned  basal_calories_burned  total_calories_burned  \
1                     NaN                 2624.0                 2624.0
2                     NaN                 2624.0                 2624.0
3                     NaN                 2624.0                 2624.0
4                     NaN                 2624.0                 2624.0
5                     NaN                 2624.0                 2624.0

   average_headphone_exposure  average_environment_exposure  isRepeated
1                         NaN                           NaN        True
2                         NaN                           NaN        True
3                         NaN                           NaN        True
4                         NaN                           NaN        True
5                         NaN                           NaN        True

In [79]:
profiles = pd.DataFrame()
profiles["user_code"] = user_counts[user_counts >10].keys()
profiles["user_count"] = user_counts[user_counts > 10].values
print(profiles.head(), profiles.tail())

    user_code  user_count
0  0d297d2410         170
1  6be5033971         162
2  fcf3ea75b0         153
3  c174f32d88         152
4  276ab22485         128      user_code  user_count
44  b325aa1406          13
45  cf7e50bcde          13
46  9b4a5ded49          12
47  29d2a4bb3a          11
48  2e94435085          11

In [80]:
# Now let's track average total calories burned per day per user
avg_daily = df.groupby("user_code")["total_calories_burned"].mean().reset_index()
avg_daily.rename(columns={"total_calories_burned": "avgDailyCalories"}, inplace=True)

profiles = profiles.merge(avg_daily, on="user_code")
print(profiles)

     user_code  user_count  avgDailyCalories
0   0d297d2410         170       2766.205882
1   6be5033971         162       1842.487654
2   fcf3ea75b0         153       2416.392157
3   c174f32d88         152       3884.631579
4   276ab22485         128       2585.859375
5   4985083f4d         127       1851.181102
6   a1c2e6b2eb         119       3366.521008
7   e8240b51a2         113       2474.292035
8   01bad5a519         113       2624.000000
9   9871ee5e7b         108       2295.261682
10  ebf2c3cb63         108       1949.000000
11  35c7355282         107       2757.168224
12  5d200bd1c6         101       1953.366337
13  295ed96279          83       1906.289157
14  b9b65b7a69          77       2258.000000
15  ad41d5b79c          73       2072.602740
16  71980b2daf          66       1683.000000
17  b523b4512b          64       2350.718750
18  d40dc56a36          60       2463.333333
19  aa036185e3          60       4841.566667
20  cdf7848d2b          59       2558.050847
21  fde84801d8          57       3520.070175
22  4c2702c3e1          56       4317.571429
23  42a99d8248          55       2810.000000
24  f9edcb7056          51       2573.784314
25  7ba5381254          45       2728.666667
26  6ecfe4a351          42       2061.333333
27  0f2d7af30c          38       2978.289474
28  866977681f          36       1896.000000
29  5efbee746a          35       2380.000000
30  1942df1c47          34       1968.000000
31  c9087bbdf7          32       2993.781250
32  cdfbcad405          32       2676.562500
33  3acfbb328e          30       2163.000000
34  425969dc69          29       2145.000000
35  f922e9b06c          27       1768.925926
36  856d41cc60          24       2073.000000
37  5228cb9439          21       2001.000000
38  4c3311ade3          21       3419.523810
39  da09fd67f1          21       2969.000000
40  1ce1d77659          19       2359.000000
41  78cc008261          19       2632.000000
42  5108b04245          17       2180.000000
43  1ed25f66e9          14       2618.000000
44  b325aa1406          13       2123.000000
45  cf7e50bcde          13       1802.000000
46  9b4a5ded49          12       2730.000000
47  29d2a4bb3a          11       2556.000000
48  2e94435085          11       2406.363636

Now let's build a function that adds average wearables dataset info to the profiles dataset

In [81]:
def avg_daily_something(profiles, something: str):
  avg_daily = df.groupby("user_code")[something].mean().reset_index()
  avg_daily.rename(columns={something: f"avg_{something}"}, inplace=True)
  return profiles.merge(avg_daily, on="user_code")

In [82]:
# create these columns (There is a better way to do this than returning
profiles= avg_daily_something(profiles, "steps_count")
profiles= avg_daily_something(profiles, "distance")
profiles=avg_daily_something(profiles, "steps_speed")

In [83]:
profiles

,user_code,user_count,avgDailyCalories,avg_steps_count,avg_distance,avg_steps_speed
0,0d297d2410,170,2766.205882,8587.292994,6815.333333,27.282821
1,6be5033971,162,1842.487654,7498.076336,5007.849624,23.107845
2,fcf3ea75b0,153,2416.392157,5316.529851,4038.857143,26.736881
3,c174f32d88,152,3884.631579,3749.774834,2527.472973,14.226061
4,276ab22485,128,2585.859375,894.277778,881.784314,24.600000
5,4985083f4d,127,1851.181102,7588.550725,5332.000000,7.392800
6,a1c2e6b2eb,119,3366.521008,9491.388889,8430.905660,17.093958
7,e8240b51a2,113,2474.292035,6369.043478,3807.153846,52.002500
8,01bad5a519,113,2624.000000,7109.415929,NaN,56.745432
9,9871ee5e7b,108,2295.261682,3105.481481,1844.096154,31.451852
10,ebf2c3cb63,108,1949.000000,3061.561798,2043.202247,41.581279
11,35c7355282,107,2757.168224,2655.086957,NaN,25.635000
12,5d200bd1c6,101,1953.366337,5387.528736,3179.023256,8.477500
13,295ed96279,83,1906.289157,NaN,NaN,NaN
14,b9b65b7a69,77,2258.000000,426.680000,265.493151,24.138095
15,ad41d5b79c,73,2072.602740,6553.671429,4641.391304,20.070806
16,71980b2daf,66,1683.000000,3165.034483,2085.754098,39.006400
17,b523b4512b,64,2350.718750,2960.490909,2094.054545,16.838235
18,d40dc56a36,60,2463.333333,6188.689655,4523.758621,30.396071
19,aa036185e3,60,4841.566667,11382.784314,3305.902439,39.131000
20,cdf7848d2b,59,2558.050847,6289.440000,5072.500000,39.567500
21,fde84801d8,57,3520.070175,3826.098039,1925.785714,33.191667
22,4c2702c3e1,56,4317.571429,9084.945946,6962.562500,54.655172
23,42a99d8248,55,2810.000000,935.259259,688.074074,16.476389
24,f9edcb7056,51,2573.784314,2401.888889,1346.111111,NaN
25,7ba5381254,45,2728.666667,3336.848485,2044.818182,24.680909
26,6ecfe4a351,42,2061.333333,5177.095238,3348.952381,7.385000
27,0f2d7af30c,38,2978.289474,1468.000000,1162.560000,20.282308
28,866977681f,36,1896.000000,NaN,1582.083333,NaN
29,5efbee746a,35,2380.000000,1042.437500,751.906250,58.328710
30,1942df1c47,34,1968.000000,813.964286,494.555556,16.512308
31,c9087bbdf7,32,2993.781250,NaN,NaN,NaN
32,cdfbcad405,32,2676.562500,3746.035714,2397.423077,43.648571
33,3acfbb328e,30,2163.000000,NaN,NaN,NaN
34,425969dc69,29,2145.000000,NaN,NaN,NaN
35,f922e9b06c,27,1768.925926,9186.346154,6252.000000,22.476800
36,856d41cc60,24,2073.000000,NaN,NaN,NaN
37,5228cb9439,21,2001.000000,NaN,NaN,NaN
38,4c3311ade3,21,3419.523810,6599.142857,3469.266667,15.680000
39,da09fd67f1,21,2969.000000,4025.428571,2935.714286,28.055714
40,1ce1d77659,19,2359.000000,NaN,NaN,NaN
41,78cc008261,19,2632.000000,NaN,2236.058824,NaN
42,5108b04245,17,2180.000000,NaN,NaN,NaN
43,1ed25f66e9,14,2618.000000,NaN,NaN,NaN
44,b325aa1406,13,2123.000000,NaN,NaN,NaN
45,cf7e50bcde,13,1802.000000,NaN,NaN,NaN
46,9b4a5ded49,12,2730.000000,NaN,NaN,NaN
47,29d2a4bb3a,11,2556.000000,NaN,NaN,NaN
48,2e94435085,11,2406.363636,NaN,NaN,NaN

## Summary

Amazing! We built a basic profiles dataset by grouping together daily wearables data by user id. This investigation allows us to learn more about the people's behavioral patterns using the wearables, rather than general daily data. Today, we learned about average daily calories, step count, distance walked, and step speed. We could use this data to find general correlations between step patterns and calories burnt. There are obvious deviations in the data already. For example: user 276ab22485 (row 4) burns about ~2585 calories despite averaging ~894 steps. Perhaps he swims or finds another way to stay active.