# HW Assignment 4: Understanding Data Analysis


Assignment goals:

- Step 1: Understand your data - what do the features mean? (May have to do some info gathering)
- Step 2: Document data context and data sampling in markdown
- Step 3: Explore and interpret data structure, descriptive statistics, data quality, and variable relationships
- Step 4: Explore data visually with appropriate visualizations
- Step 5: Discuss and implement strategies for Handling Missing Values, Removing Duplicates, and Handling Outliers
- Step 6: Perform data transformation as appropriate
- Step 7: Create at least one new feature and document your approach
- Step 8: Include a discussion around data quality assessment, including data profiling, data completeness, data accuracy, data consistency, data integrity, and data lineage and provenance

## Step 1: Understanding the Data

The following data contains information on patients who have had the COVID 19 disease and what there experiences were. The data is divided into the subsection as seen below. 

### Patient Data 

The following data has key information about the patient - what there code is what there gender is where they are from and when there symotoms started

**Name of Variable** | **Description** | **Units** |
| :------- | :------: | -------: |
user_code | Unique user ID | NA	|
gender | Gender: m/f/other or empty	| NA |
age_range | Age range	| years |
city | City	| Location |
country	| Country | Location |
height | Height | cm |
weight| Weight | kg |
symptoms_onset | The onset date of the symptoms of the disease | MM/DD/YYYY |	

### Heart Data

The following is a data table for the heart rate variability, plus some data on how the users feels

| **Heart Rate Monitoring Data**    | **Description**                                                                         | **Units**        |
|---------------|-----------------------------------------------------------------------------------------|------------------|
| user\_code    | Unique user ID                                                                          |                  |
| rr\_code      | Unique measurement ID                                                                   |                  |
| measurement\_datetime  | Measurement datetime in YYYY-MM-DD hh:mm:ss format                             |                  |
| time\_of\_day | Time of day: 'evening', 'morning', 'night' or 'day'                                     |                  |
| bpm           | Heart rate during measurement                                                           | beats per minute |
| meanrr        | Mean RR — average time between each heartbeat.                                          | milliseconds     |
| mxdmn         | MxDMn — the difference between highest and lowest cardio interval values.               | seconds          |
| sdnn          | SDNN — standard deviation of normal heartbeat intervals.                                | milliseconds     |
| rmssd         | rMSSD — root mean square of successive differences for consecutive intervals.           | milliseconds     |
| pnn50         | PNN50 — percent of RR-intervals that fall outside a 50 ms range of the average.         | %                |
| mode          | Moda — the most common cardio interval length in a measurement.                         | milliseconds     |
| amo           | AMo50 — mode amplitude.                                                                 | %/50milliseconds |
| lf            | LF — the power of low frequency waves.                                                  | milliseconds²    |
| hf            | HF — the power of high frequency waves.                                                 | milliseconds²    |
| vlf           | VLF — power of very low frequency waves.                                                | milliseconds²    |
| lfhf          | LF/HF — ratio of low to high frequency waves.                                           |                  |
| total\_power  | Total Power — the total power of HF, LF, and VLF waves generated by the heart.          | milliseconds²    |
| how\_feel     | Health score — answers to "How do you feel physically?" in the post-measurement survey. |                  |
| how\_mood     | Mood score — answers to "How is your mood?" in the post-measurement survey.             |                  |
| how\_sleep    | Sleep score —answers to "How did you sleep?" in the post-measurement survey.            |                  |
| rr\_data      | Intervals in milliseconds between consecutive heart beats as a comma-separated string   |                  |
| tags          | Tags assigned by user as a comma-separated string                                       |

### Blood Pressure Data

The following data is data on the blood pressure and different values to correlate stress recovery from the patient

| **Variables**              |  **Description**                                                                                                                                      | **Units**              |
|---------------|-----------------------------------------------------------------------------------------|------------------|
| user\_code                 | Unique user ID                                                                                                                                        |                        |
| measurement_datetime       | Measurement  datetime in YYYY-MM-DD hh:mm:ss format                                                                                                   |                        |
| diastolic                  | Diastolic blood pressure                                                                                                                              | millimeters of mercury |
| systolic                   | Systolic blood pressure                                                                                                                               | millimeters of mercury |
| functional\_changes\_index | FCI blood index — functional changes index. An assessment of how well the body can adapt to stressors. Takes height, weight, and gender into account. |                        |
| circulatory\_efficiency    | BCE blood index — blood circulation efficiency. Shows the body's readiness to cope with pressure based on blood pressure readings.                    |                        |
| kerdo\_vegetation\_index   | Kerdo index — balance between stress and recovery based on blood pressure: a physiological indicator derived from blood pressure and pulse measurements that assesses the ratio of sympathetic and parasympathetic nervous system activity in the body's cardiovascular regulation                                                                            |                        |
| robinson\_index            | Robinson’s index — the capacity of the cardiovascular system based on systolic blood pressure.                                                        |

### Heart Rate Raw Data

Contains raw heart rate intervals -

| **Heart_Rate_Variables**           | **Description**                                                               | **Units** |
|----------------------|-------------------------------------------------------------------------------|-----------|
| user\_code           | Unique user ID                                                                |           |
| daytime              | Measurement datetime in YYYY-MM-DD hh:mm:ss format                            |           |
| heart\_rate          | Heart rate                                                                    | beats per minute |
| is\_resting          | Was heart rate measured during times of rest                                  |

### Exercise Data and Body Temp and Pulse

Contains summary of the users heart rate, temp, steps and exercise per day

| **Summary_Variables_pulse_and_Exercise**                          | **Description**                                                                                                                  | **Units**        |
|-------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------|
| user\_code                          | Unique user ID                                                                                                                   |                  |
| day                                 | Measurement date in YYYY-MM-DD format                                                                                            |                  |
| resting\_pulse                      | Resting heart rate                                                                                                               | beats per minute |
| pulse\_average                      | Heart rate                                                                                                                       | beats per minute |
| pulse\_min                          | Min heart rate                                                                                                                   | beats per minute |
| pulse\_max                          | Max heart rate                                                                                                                   | beats per minute |
| average\_spo2\_value                | Oxygen saturation                                                                                                                | %                |
| body\_temperature\_avg              | Body temperature                                                                                                                 | °C               |
| stand\_hours\_total                 | Hours spend standing                                                                                                             | hours            |
| steps\_count                        | Steps                                                                                                                            | steps            |
| distance                            | Walking & running distance                                                                                                       | meters           |
| steps\_speed                        | Steps cadence — number of steps per minute.                                                                                      | steps per minute |
| total\_number\_of\_flights\_climbed | Flights climbed                                                                                                                  | flights          |
| active\_calories\_burned            | Active kcal — how many calories you burned as a result of activity.                                                              | kilocalories     |
| basal\_calories\_burned             | Resting kcal — how many calories you burned at rest just by keeping your body's systems running: digesting food, breathing, etc. | kilocalories     |
| total\_calories\_burned             | Calories burned                                                                                                                  | kilocalories     |
| average\_headphone\_exposure        | Average headphone audio levels                                                                                                   | decibel          |
| average\_environment\_exposure      | Average environmental sound levels                                                                                               | decibel          |

### Sleep Data 

Provides details on sleep

| **Sleep Variables**             | **Description**                                               | **Units**        |
|------------------------|---------------------------------------------------------------|------------------|
| user\_code             | Unique user ID                                                |                  |
| day                    | Measurement date in YYYY-MM-DD format                         |                  |
| sleep\_begin           | Sleep start date and time in YYYY-MM-DD hh:mm:ss format       |                  |
| sleep\_end             | Sleep end date and time in YYYY-MM-DD hh:mm:ss format         |                  |
| sleep\_duration        | Time asleep                                                   | hours            |
| sleep\_awake\_duration | Time awake — amount of time you spent in bed, but not asleep. | hours            |
| sleep\_rem\_duration   | REM sleep — rapid eye movement sleep                          | hours            |
| sleep\_light\_duration | Light sleep                                                   | hours            |
| sleep\_deep\_duration  | Deep sleep                                                    | hours            |
| pulse\_min             | Min heart rate                                                | beats per minute |
| pulse\_max             | Max heart rate                                                | beats per minute |
| pulse\_average         | Heart rate                                                    | beats per minute |



### User Survey 

Surveys 

Contains results of health-related surveys that users take in Welltory app

| Column     | Description                                         | Units   |
|------------|-----------------------------------------------------|---------|
| user_code  | Unique user ID                                      |         |
| scale      | Survey code (see section 'Survey scale description' for details)|         |
| created_at | Date when user took the survey in YYYY-MM-DD format |         |
| value      | User's result                                       |         |
| text       | Text interpretation of user's result                |         |

**Survey scale description**

| Scale             | Description                                                                                                                                                             |   Value | Meaning                                                    |
|:------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|:-----------------------------------------------------------|
| S_COVID_SYMPTOMS  | How long the user has been experiencing symptoms                                                                                                                        |       1 | Less than 3 days                                           |
| S_COVID_SYMPTOMS  | How long the user has been experiencing symptoms                                                                                                                        |       2 | 3 to 6 days                                                |
| S_COVID_SYMPTOMS  | How long the user has been experiencing symptoms                                                                                                                        |       3 | 7 to 14 days                                               |
| S_COVID_SYMPTOMS  | How long the user has been experiencing symptoms                                                                                                                        |       4 | More than 14 days                                          |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       1 | User isn’t experiencing symptom                            |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       2 | Very mild                                                  |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       3 | Mild                                                       |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       4 | Moderate                                                   |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       5 | Severe                                                     |
| S_COVID_COUGH     | Symptom intensity: Coughing                                                                                                                                             |       6 | Extremely severe                                           |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       1 | User isn’t experiencing symptom                            |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       2 | Very mild                                                  |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       3 | Mild                                                       |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       4 | Moderate                                                   |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       5 | Severe                                                     |
| S_COVID_FEVER     | Symptom intensity: Fever                                                                                                                                                |       6 | Extremely severe                                           |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       1 | User isn’t experiencing symptom                            |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       2 | Very mild                                                  |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       3 | Mild                                                       |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       4 | Moderate                                                   |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       5 | Severe                                                     |
| S_COVID_BREATH    | Symptom intensity: Shortness of breath                                                                                                                                  |       6 | Extremely severe                                           |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       1 | User isn’t experiencing symptom                            |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       2 | Very mild                                                  |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       3 | Mild                                                       |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       4 | Moderate                                                   |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       5 | Severe                                                     |
| S_COVID_FATIGUE   | Symptom intensity: Fatigue                                                                                                                                              |       6 | Extremely severe                                           |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       1 | User isn’t experiencing symptom                            |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       2 | Very mild                                                  |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       3 | Mild                                                       |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       4 | Moderate                                                   |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       5 | Severe                                                     |
| S_COVID_PAIN      | Symptom intensity: Pain or pressure in the chest                                                                                                                        |       6 | Extremely severe                                           |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       1 | User isn’t experiencing symptom                            |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       2 | Very mild                                                  |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       3 | Mild                                                       |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       4 | Moderate                                                   |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       5 | Severe                                                     |
| S_COVID_CONFUSION | Symptom intensity: Confusion                                                                                                                                            |       6 | Extremely severe                                           |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       1 | User isn’t experiencing symptom                            |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       2 | Very mild                                                  |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       3 | Mild                                                       |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       4 | Moderate                                                   |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       5 | Severe                                                     |
| S_COVID_TROUBLE   | Symptom intensity: Trouble breathing                                                                                                                                    |       6 | Extremely severe                                           |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       1 | User isn’t experiencing symptom                            |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       2 | Very mild                                                  |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       3 | Mild                                                       |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       4 | Moderate                                                   |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       5 | Severe                                                     |
| S_COVID_BLUISH    | Symptom intensity: Bluish face or lips                                                                                                                                  |       6 | Extremely severe                                           |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       1 | User isn’t experiencing symptom                            |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       2 | Very mild                                                  |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       3 | Mild                                                       |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       4 | Moderate                                                   |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       5 | Severe                                                     |
| S_COVID_OVERALL   | Overall state                                                                                                                                                           |       6 | Extremely severe                                           |
| S_CORONA          | An assessment of the user’s symptoms which shows how likely it is that the user has coronavirus                                                                         |       1 | User has some of the symptoms associated with coronavirus  |
| S_CORONA          | An assessment of the user’s symptoms which shows how likely it is that the user has coronavirus                                                                         |       2 | Symptoms are characteristic of coronavirus                 |
| S_CORONA          | An assessment of the user’s symptoms which shows how likely it is that the user has coronavirus                                                                         |       3 | Symptoms are non-specific                                  |
| S_CORONA          | An assessment of the user’s symptoms which shows how likely it is that the user has coronavirus                                                                         |       4 | Symptoms are not characteristic of coronavirus             |
| S_CORONA          | An assessment of the user’s symptoms which shows how likely it is that the user has coronavirus                                                                         |       5 | No symptoms of coronavirus                                 |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       1 | A 30% chance of developing coronary heart disease          |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       2 | A 50% chance of developing coronary heart disease          |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       3 | A 20% chance of developing coronary heart disease          |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       4 | A 10% chance of developing coronary heart disease          |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       5 | Less than 10% chance of developing coronary heart disease  |
| S_HEART           | An assessment of a user’s chances to develop coronary heart disease based on their lifestyle and habits. Based on Framingham Risk Score for Hard Coronary Heart Disease |       6 | Less than 3% chance of developing coronary heart disease   |
| S_HEART_1         | Whether the user is a smoker                                                                                                                                            |       1 | User is a smoker                                           |
| S_HEART_2         | Whether the user has diabetes and/or is overweight                                                                                                                      |       1 | User has diabetes and is overweight                        |
| S_HEART_22        | Whether the user has diabetes and/or is overweight                                                                                                                      |       1 | User has diabetes and is not overweight                    |
| S_HEART_3         | Whether the user has high cholesterol levels                                                                                                                            |       1 | User has high cholesterol levels                           |
| S_HEART_4         | Whether the user has high BP                                                                                                                                            |       1 | User has high BP                                           |
| S_HEART_5         | Whether the user takes BP meds                                                                                                                                          |       1 | User has high BP and does not take meds                    |
| S_HEART_6         | Whether the user is highly stressed                                                                                                                                     |       1 | User has high stress                                       |
| S_HEART_7         | Whether the user is overweight                                                                                                                                          |       1 | User is overweight                                         |
| S_HRA_MONTH       | How far along in their pregnancy the user is                                                                                                                            |       1 | User is less than 3 months pregnant when taking the test   |
| S_HRA_MONTH       | How far along in their pregnancy the user is                                                                                                                            |       2 | User is less than 3-4 months pregnant when taking the test |
| S_HRA_MONTH       | How far along in their pregnancy the user is                                                                                                                            |       3 | User is less than 5-6 months pregnant when taking the test |
| S_HRA_MONTH       | How far along in their pregnancy the user is                                                                                                                            |       4 | User is more than 7 months pregnant when taking the test   |
| S_HRA_ASTHMA      | Whether the user has asthma or bronchial spasm                                                                                                                          |       1 | User has asthma or bronchial spasm                         |
| S_HRA_ALLERG      | Whether the user has allergies                                                                                                                                          |       1 | User has allergies                                         |
| S_HRA_LUNG        | Whether the user has lung diseases                                                                                                                                      |       1 | User has lung diseases                                     |
| S_HRA_KIDNEY      | Whether the user has kidney problems                                                                                                                                    |       1 | User has kidney problems                                   |
| S_HRA_LIVER       | Whether the user has liver problems                                                                                                                                     |       1 | User has liver problems                                    |
| S_HRA_CHOL        | Whether the user has high cholesterol                                                                                                                                   |       1 | User has high cholesterol                                  |
| S_HRA_DBT         | Whether the user has any type of diabetes                                                                                                                               |       1 | User has type 1 diabetes                                   |
| S_HRA_DBT         | Whether the user has any type of diabetes                                                                                                                               |       2 | User has type 2 diabetes                                   |
| S_HRA_ARR         | Whether the user has arrhythmia or other heart rhythm disorders                                                                                                         |       1 | User has arrhythmia or other heart rhythm disorders        |
| S_HRA_HEART       | Whether the user has heart disease, blood pressure problems                                                                                                             |       1 | User has heart disease, blood pressure problems            |
| S_HRA_AFTER       | Whether the user s recovering after a heart attack                                                                                                                      |       1 | User is recovering after a heart attack                    |
| S_HRA_HBP         | Whether the user has high blood pressure                                                                                                                                |       1 | User has high blood pressure                               |
| S_HRA_LBP         | Whether the user has low BP                                                                                                                                             |       1 | User has low BP                                            |
| S_HRA_THYR        | Whether the user has thyroid problems                                                                                                                                   |       1 | User has hypothyroidism                                    |
| S_HRA_THYR        | Whether the user has thyroid problems                                                                                                                                   |       2 | User has hyperthyroidism                                   |
| S_HRA_EPILEPSY    | Whether the user has epilepsy                                                                                                                                           |       1 | User has epilepsy                                          |
| S_HRA_BONE        | Whether the user has musculoskeletal disorders                                                                                                                          |       1 | User has musculoskeletal disorders                         |
| S_HRA_JOINTS      | Whether the user has arthritis                                                                                                                                          |       1 | User has arthritis                                         |
| S_HRA_OSTEO       | Whether the user has osteoporosis                                                                                                                                       |       1 | User has osteoporosis                                      |
| S_HRA_NECK        | Whether the user has neck pain                                                                                                                                          |       1 | User has neck pain                                         |
| S_HRA_JOINT       | Whether the user has joint pain                                                                                                                                         |       1 | User has joint pain                                        |
| S_HRA_FIBRO       | Whether the user has fibromyalgia                                                                                                                                       |       1 | User has fibromyalgia                                      |
| S_HRA_HEAD        | Whether the user has headaches/migraines                                                                                                                                |       1 | User has headaches                                         |
| S_HRA_HEAD        | Whether the user has headaches/migraines                                                                                                                                |       2 | User has migraines                                         |
| S_HRA_SLEEP       | Whether the user has sleep problems                                                                                                                                     |       1 | User has sleep problems                                    |
| S_HRA_DEP         | Whether the user has depression                                                                                                                                         |       1 | User has depression                                        |
| S_HRA_ANX         | Whether the user has anxiety                                                                                                                                            |       1 | User has anxiety                                           |
| S_HRA_PANIC       | Whether the user has panic attacks                                                                                                                                      |       1 | User has panic attacks                                     |
| S_HRA_EDEMA       | Whether the user has edema                                                                                                                                              |       1 | User has edema                                             |
| S_HRA_CUSHING     | Whether the user has Cushing's syndrome                                                                                                                                 |       1 | User has Cushing's syndrome                                |
| S_HRA_D           | Whether the user has vitamin D deficiency                                                                                                                               |       1 | User has vitamin D deficiency                              |
| S_HRA_OVARY       | Whether the user has polycystic ovaries                                                                                                                                 |       1 | User has polycystic ovaries                                |
| S_HRA_VARI        | Whether the user has varicose veins                                                                                                                                     |       1 | User has varicose veins                                    |
| S_HRA_ENDO        | Whether the user has endometriosis                                                                                                                                      |       1 | User has endometriosis                                     |
| S_HRA_HORM        | Whether the user’s  hormones are out of balance                                                                                                                         |       1 | User’s  hormones are out of balance                        |
| S_SMOKING         | Whether the user is a smoker                                                                                                                                            |       1 | User recently quit smoking                                 |
| S_SMOKING         | Whether the user is a smoker                                                                                                                                            |       2 | User is a smoker                                           |
| S_HRA_PMS         | Whether the user has PMS                                                                                                                                                |       1 | User has PMS                                               |
| S_HRA_HEAVY       | Whether the user has heavy periods                                                                                                                                      |       1 | User has heavy periods                                     |
| S_HRA_IRR         | Whether the user has irregular periods                                                                                                                                  |       1 | User has irregular periods                                 |
| S_HRA_PERPAIN     | Whether the user has painful periods                                                                                                                                    |       1 | User has painful periods                                   |
| S_HRA_SUGAR       | Whether the user has high blood sugar                                                                                                                                   |       1 | User has high blood sugar                                  |
| S_HRA_COLDS       | Whether the user has frequent colds                                                                                                                                     |       1 | User has frequent colds                                    |
| S_HRA_ANEMIA      | Whether the user has anemia                                                                                                                                             |       1 | User has anemia                                            |
| S_HRA_BIPOLAR     | Whether the user is bipolar                                                                                                                                             |       1 | User is bipolar                                            |
| S_HRA_OCD         | Whether the user has OCD                                                                                                                                                |       1 | User has OCD                                               |
| S_HRA_POST        | Whether the user has PTSD                                                                                                                                               |       1 | User has PTSD                                              |
| S_HRA_SKIN        | Whether the user has skin problems                                                                                                                                      |       2 | User has rosacea                                           |
| S_HRA_SKIN        | Whether the user has skin problems                                                                                                                                      |       3 | User has psoriasis                                         |
| S_HRA_SKIN        | Whether the user has skin problems                                                                                                                                      |       1 | User has ecsema                                            |
| S_HRA_VIT         | Whether the user takes vitamins/nootropics                                                                                                                              |       1 | User takes vitamins/nootropics                             |
| S_HRA_VIT         | Whether the user takes vitamins/nootropics                                                                                                                              |       3 | User doesn’t take vitamins/nootropics                      |
| S_HRA_ALC         | How much alcohol the user consumes on a regular basis                                                                                                                   |       1 | User drinks a lot of alcohol                               |
| S_HRA_ALC         | How much alcohol the user consumes on a regular basis                                                                                                                   |       2 | User doesn’t drink alcohol                                 |
| S_HRA_ALC         | How much alcohol the user consumes on a regular basis                                                                                                                   |       3 | User drinks little alcohol                                 |
| S_HRA_ALC         | How much alcohol the user consumes on a regular basis                                                                                                                   |       4 | User drinks an average amount of alcohol                   |
| S_DIABETES        | An assessment of the user’s chances of developing Type 2 Diabetes based on their lifestyle and habits. Based on research by Finnish Diabetes Association                |       1 | 1% chance of developing Type 2 diabetes                    |
| S_DIABETES        | An assessment of the user’s chances of developing Type 2 Diabetes based on their lifestyle and habits. Based on research by Finnish Diabetes Association                |       2 | 4% chance of developing Type 2 diabetes                    |
| S_DIABETES        | An assessment of the user’s chances of developing Type 2 Diabetes based on their lifestyle and habits. Based on research by Finnish Diabetes Association                |       3 | 15% chance of developing Type 2 diabetes                   |
| S_DIABETES        | An assessment of the user’s chances of developing Type 2 Diabetes based on their lifestyle and habits. Based on research by Finnish Diabetes Association                |       4 | 30% chance of developing Type 2 diabetes                   |
| S_DIABETES        | An assessment of the user’s chances of developing Type 2 Diabetes based on their lifestyle and habits. Based on research by Finnish Diabetes Association                |       5 | 50% chance of developing Type 2 diabetes                   |
| S_DIAB_REASON1    | Whether the user’s waist circumference is within the norm                                                                                                               |       1 | Waist circumference is within the norm                     |
| S_DIAB_REASON2    | Whether the user is active enough                                                                                                                                       |       1 | Is active enough                                           |
| S_DIAB_REASON3    | Whether the user eats healthy                                                                                                                                           |       1 | Eats healthy                                               |
| S_DIAB_REASON4    | Whether the user has BP problems                                                                                                                                        |       1 | No BP problems                                             |
| S_DIAB_REASON5    | Whether the user’s blood sugar is within the norm when taking the test                                                                                                  |       1 | Blood sugar is within the norm when taking the test        |
| S_DIAB_REASON6    | Whether the user has a family history of diabetes                                                                                                                       |       1 | No family history of diabetes                              |

Contains data based on heart rate variability (HRV) measurements collected from COVID-19 participants via the Welltory app
Note all data was found here: [Link to Heart Rate Variability Data from Welltory App](https://github.com/Welltory/hrv-covid19/tree/master)

## Step 2: Document data context and data sampling

The data was collected via three different sources with the sampling sources discussed below 

    1) Heart rate variability - Bluetooth enabled heart monitor (this was collected via a sensor)
    2) Data for Apple Watch/ Garmin - Some users may have exercise garments that help track data and heart rates
    3) Clinically validated tests - Users filled out a survey based on how they were feeling

It is from an open source code which is based off a study done from Welltory

## Step 3: Explore and interpret data structure, descriptive statistics, data quality, and variable relationships


### Data Structure

In [33]:
## Pulling Data Structure 

import pandas as pd
import numpy as np
from pathlib import Path                #note this was written copilot to fix not being able to pull the data from the COVID_data folder
import matplotlib.pyplot as plt
import seaborn as sns
import os


# reading each csv and creating a dataframe for each (use correct filenames)
data_bp = pd.read_csv('./COVID_data/blood_pressure.csv')
data_hr = pd.read_csv('./COVID_data/heart_rate.csv')
data_hrv_measure = pd.read_csv('./COVID_data/hrv_measurements.csv')
data_survey = pd.read_csv('./COVID_data/surveys.csv')
data_sleep = pd.read_csv('./COVID_data/sleep.csv')
data_participants = pd.read_csv('./COVID_data/participants.csv')
data_scales = pd.read_csv('./COVID_data/scales_description.csv')
data_wearables = pd.read_csv('./COVID_data/wearables.csv')

# quick verification (print shapes)
print('data_bp:', data_bp.shape)
print('data_hr:', data_hr.shape)
print('data_hrv_measure:', data_hrv_measure.shape)
print('data_survey:', data_survey.shape)
print('data_sleep:', data_sleep.shape)
print('data_participants:', data_participants.shape)
print('data_scales:', data_scales.shape)
print('data_wearables:', data_wearables.shape)

data_bp: (721, 8)
data_hr: (523783, 4)
data_hrv_measure: (3245, 22)
data_survey: (2259, 5)
data_sleep: (425, 12)
data_participants: (185, 8)
data_scales: (148, 4)
data_wearables: (3098, 18)




### Descriptive Statistics

In [34]:
print(data_bp.head())

print(data_bp['measurement_datetime'].nunique())

print(pd.to_datetime(data_bp['measurement_datetime']).dt.date.nunique())
print(pd.to_datetime(data_bp['measurement_datetime']).dt.date.min())
print(pd.to_datetime(data_bp['measurement_datetime']).dt.date.max())



data_bp.describe()
print("number of NaN values:", data_bp.isna().sum().sum())

data_bp_clean = data_bp.dropna()

print(data_bp_clean.describe())
data_bp_clean.shape

print('data_bp:', data_bp.shape)
print('data_hr:', data_hr.shape)
print('data_hrv_measure:', data_hrv_measure.shape)
print('data_survey:', data_survey.shape)
print('data_sleep:', data_sleep.shape)
print('data_participants:', data_participants.shape)
print('data_scales:', data_scales.shape)
print('data_wearables:', data_wearables.shape)

    user_code  measurement_datetime  diastolic  systolic  \
0  01bad5a519  2020-04-29  22:33:33        100       150
1  01bad5a519  2020-04-30  01:33:33        100       150
2  01bad5a519  2020-04-30  09:16:38         95       140
3  01bad5a519  2020-04-30  12:16:38         95       140
4  01bad5a519  2020-05-01  06:58:06         80       130

   functional_changes_index  circulatory_efficiency  kerdo_vegetation_index  \
0                       NaN                     NaN                     NaN
1                       NaN                     NaN                     NaN
2                      3.38                  4545.0                     6.0
3                       NaN                     NaN                     NaN
4                      2.89                  4000.0                     NaN

   robinson_index
0             NaN
1             NaN
2           141.4
3             NaN
4           104.0
719
120
2019-12-31
2020-06-19
number of NaN values: 1704
        diastolic    systolic  functional_changes_index  \
count  283.000000  283.000000                283.000000
mean    80.593640  119.395760                  2.599788
std      8.594957   10.757098                  0.288765
min     40.000000   87.000000                  1.680000
25%     75.000000  112.000000                  2.440000
50%     81.000000  120.000000                  2.580000
75%     87.000000  126.000000                  2.725000
max    101.000000  157.000000                  3.510000

       circulatory_efficiency  kerdo_vegetation_index  robinson_index
count              283.000000              283.000000      283.000000
mean              2738.353074              -15.498233       84.795936
std                757.525826               18.681233       14.382719
min               1300.000000              -76.000000       49.500000
25%               2250.500000              -29.000000       75.935000
50%               2660.000000              -17.000000       83.220000
75%               3076.500000               -5.000000       93.170000
max               7875.000000               45.000000      164.850000
data_bp: (721, 8)
data_hr: (523783, 4)
data_hrv_measure: (3245, 22)
data_survey: (2259, 5)
data_sleep: (425, 12)
data_participants: (185, 8)
data_scales: (148, 4)
data_wearables: (3098, 18)

In [25]:
print(data_hr.head())

print(data_hr['datetime'].nunique())

print(pd.to_datetime(data_hr['datetime']).dt.date.nunique())
print(pd.to_datetime(data_hr['datetime']).dt.date.min())
print(pd.to_datetime(data_hr['datetime']).dt.date.max())

data_hr.describe()

    user_code             datetime  heart_rate  is_resting
0  007b8190cf  2020-04-26 04:49:25          70           0
1  01bad5a519  2020-04-23 06:21:03          74           0
2  01bad5a519  2020-04-23 09:46:01          82           0
3  01bad5a519  2020-04-23 14:05:06          90           0
4  01bad5a519  2020-04-24 03:41:18          72           0
506422
171
2020-01-01
2020-06-19

          heart_rate     is_resting
count  523783.000000  523783.000000
mean       90.856626       0.005546
std        25.054152       0.074266
min        10.000000       0.000000
25%        71.000000       0.000000
50%        87.000000       0.000000
75%       108.000000       0.000000
max       232.000000       1.000000

In [31]:

print(data_hrv_measure.head())

print(data_hrv_measure['datetime'].nunique())

print(pd.to_datetime(data_hrv_measure['datetime']).dt.date.nunique())
print(pd.to_datetime(data_hrv_measure['datetime']).dt.date.min())
print(pd.to_datetime(data_hrv_measure['datetime']).dt.date.max())

data_hrv_measure.describe()

    user_code     rr_code measurement_datetime time_of_day  bpm  meanrr  \
0  007b8190cf  10489a6aea  2020-04-21 21:23:08     morning   75  795.90
1  007b8190cf  9610d4d4dc  2020-04-26 11:19:25     morning   70  858.00
2  013f6d3e5b  f3de056155  2020-05-15 04:14:21       night   83  724.10
3  013f6d3e5b  b04489e32f  2020-05-19 03:06:02       night   75  802.64
4  01bad5a519  ac52c706c6  2019-12-31 09:07:43     morning   78  768.07

   mxdmn    sdnn   rmssd  pnn50  ...     lf      hf     vlf   lfhf  \
0   0.12  45.802  54.174  15.15  ...  508.0  1076.0   267.0  0.472
1   0.11  32.889  33.022  16.16  ...  409.0   310.0   176.0  1.319
2   0.17  54.811  65.987  17.17  ...  432.0   881.0   194.0  0.490
3   0.20  72.223  70.039  22.22  ...  814.0  1487.0  1719.0  0.547
4   0.10  29.650  21.196   4.04  ...  489.0   128.0    96.0  3.820

   total_power  how_feel  how_mood  how_sleep  \
0       1851.0         0        -1        NaN
1        895.0         0         0        0.0
2       1507.0        -1        -2        NaN
3       4020.0         0         0        NaN
4        713.0         0         0        0.0

                                                tags  \
0  COVID-19; Workout; Sex; Hobby; Studying; Sleep...
1                                                NaN
2  COVID-19; Fast/Diet; Hungry; Tired; Fever; I c...
3                                                NaN
4                                                NaN

                                             rr_data
0  819,1008,831,847,785,778,866,839,801,793,846,8...
1  888,775,811,883,890,894,894,899,893,889,890,83...
2  694,832,642,801,751,716,737,742,773,760,701,73...
3  821,817,771,805,833,788,747,724,792,825,775,75...
4  741,740,734,737,740,731,751,747,745,728,747,76...

[5 rows x 22 columns]

KeyError: 'datetime'



### Variable Relationships

28

          heart_rate     is_resting
count  523783.000000  523783.000000
mean       90.856626       0.005546
std        25.054152       0.074266
min        10.000000       0.000000
25%        71.000000       0.000000
50%        87.000000       0.000000
75%       108.000000       0.000000
max       232.000000       1.000000

## Step 4: Explore data visually with appropriate visualizations

## Step 5: Discuss and implement strategies for Handling Missing Values, Removing Duplicates, and Handling Outliers

## Step 6: Perform data transformation as appropriate

## Repeating Step 4: With Implemented Strategies

## Step 7: Create at least one new feature and document your approach

## Step 8: Include a discussion around data quality assessment, including data profiling, data completeness, data accuracy, data consistency, data integrity, and data lineage and provenance